---
- hosts: all
  gather_facts: false
  connection: local
  
  vars:
    vsphere_host: "abc.co.nz"
    vsphere_user: "xxx"
    vsphere_datacenter: "xyz"
    vsphere_folder: "/sbc"
    vsphere_datastore: "xxxxxxxxx"
    vsphere_cluster: "xxxxxx"
    guest_network: xxxx
    guest_netmask: xxxx
    guest_gateway: xxxx
    guest_dns_server: xxxx
    guest_domain_name: xxxx
    guest_id: centos7_64Guest
    guest_memory: 2048
    guest_vcpu: 2
    guest_template: CentOS7TPL
    guest_name: xxxx
    guest_ip: xxxx
    esxi_host: "xxxx"
    notes: "Created by Ansible at"
  
  roles:
     - deploy_vmware_guest
     #- other roles to execute directly inside VM after deployment
