---

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  
- name: restart server
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  ignore_errors: true
  
- name: Pause for 180 seconds
  pause: 
    minutes=3
  
- name: wait for the server to restart
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 60
