---

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  
- name: restart server
  command: /sbin/reboot
  async: 0
  poll: 0
  ignore_errors: true
  
- name: Pause for 180 seconds
  pause: minutes=3
  
- name: wait for the server to restart
  local_action: wait_for host={{ inventory_hostname }}
    port=22
    delay=15
    timeout=300
    state=started
    connect_timeout=15
  
- name: restarting ntpserver
  service:
    name: ntpd
    state: restarted
    enabled: yes
