---
- stat: path={{ file1 }}
  register: p

- name: create a file
  file: path={{ file1 }} 
        owner=root
        group=sys
        mode=0555
        state={{ "file" if  p.stat.exists else "touch"}}
