---
- stat: path={{ sfile }}
  register: p

- name: create a file
  file: path={{ sfile }} 
        owner=root
        group=sys
        mode=0555
        state={{ "file" if  p.stat.exists else "touch"}}
