---

# Create a new VM from a template

- name: VM from template
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: aklvc01.freightways.co.nz
    esxhost: aklesx01.freightways.co.nz
    datastore: MARVIN-Virtual-SAN-Datastore-d00e6ea5-93d6-4aa4-bb9c-acb101a45c13
    network: "PrimaryCore_1001"
    vmtemplate: CentOS7TPL
    vmcluster: MARVIN-Virtual-SAN-Cluster-d00e6ea5-93d6-4aa4-bb9c-acb101a45c13
    notes: Created by Ansible
    dumpfacts: False
    
  tasks:
    - name: Check for required variables
      fail: msg="Must pass name and group to -e"
      when: name is not defined or group is not defined

    - name: Check for vSphere access parameters
      fail: msg="Must set vcenter_user and vcenter_pass in a Vault"
      when: (vcenter_user is not defined) or (vcenter_pass is not defined)

    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: BOX
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ disk_size | default(20) }}"
            type: thin
            datastore: "{{ datastore }}"
        nic:
          - type: vmxnet3
            network: "{{ network }}"
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present
      register: newvm

    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ name }}"
