---
# get date
- set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"

# Create a VM from a template
- name: create the VM
  vmware_guest:
    hostname: xxx
    username: xxx
    password: '{{ vsphere_password }}'
    validate_certs: no
    datacenter: xxx
    cluster: '{{ vsphere_cluster }}'
    name: xxx
    state: poweredon
    template: Centos7_64Guest
    guest_id: '{{ guest_id }}'
    annotation: "{{ notes }} - {{ creationdate }}"
    hardware:
      memory_mb: 2048
      num_cpus: 2
    disk:
    - datastore: '{{ vsphere_datastore }}'
      size_gb: 30
      
    networks:
    - name: PrimaryCore_1001
      
  delegate_to: localhost
  register: deploy
