---
- name: create c:\Temp
  win_file:
    path: C:\Temp
    state: directory

- name: Turn off windows firewall
  win_command: netsh advfirewall set allprofiles state off
  register: netsh_out

- name: disable hibernate
  win_command: powercfg.exe –h off
  register: powercfg_out
  
- name: install telnet client
  win_feature:
    name: 
    - telnet-client
    state: present
