---

- name: create c:\Temp
  win_shell: |
    New-Item -Path C:\temp -ItemType Directory

- name: Turn off windows firewall
  win_command: netsh advfirewall set allprofiles state off
  register: netsh_out

- name: install telnet client
  win_feature:
    name: Telnet-Client
    state: present
    restart: false
    source: C:\Windows\winsxs

- name: Install the Virtual C 
  win_package:
    path: http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe
    product_id: '{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}'
    arguments: /install /passive /norestart

- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Install Chrome
  win_chocolatey:
    name: google-chrome-x64
    state: present
    
- name: Copy 7 Zip file to c:\temp
  win_copy:
    src: files/7z1805-x64.msi
    dest: c:\temp\7z1805-x64.msi

- name: Install 7 zip
  win_package:
    path: C:\temp\7z1805-x64.msi
    product_id: '{23170F69-40C1-2702-1805-000001000000}'
    state: present

- name: create local group to contain new users
  win_group:
    name: LocalGroup
    description: Allow Access to c:\Development folder
    
- name: create local user
  win_user:
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    groups: localGroup
    update_password: on_create
    password_never_expired: yes
  with_items:
  - name: user1
    password: Password1
  - name: user2
    password: Password2

- name: create Development Folder
  win_file:
    path: C:\Development
    state: directory

- name: set ACL of Development folder
  win_acl:
    path: C:\Development
    rights: FullControl
    state: present
    type: allow
    user: LocalGroup

- name: install xWebAdministration module
  win_psmodule:
    name: xWebAdministration
    state: present

- name: install IIS features that are required
  win_dsc:
    resource_name: WindowsFeature
    Name: '{{item}}'
    Ensure: Present
  with_items:
  - Web-Server
  - Web-Asp-Net45

- name: setup web content
  win_dsc:
    resource_name: File
    DestinationPath: C:\inetpub\IISSite\index.html
    Type: File
    Contents: |
      <html>
      <head><title>IIS Site</title></head>
      <body>This is the body</body>
      </html>
    Ensure: present

- name: create new website
  win_dsc:
    resource_name: xWebsite
    Name: NewIISSite
    State: Started
    PhysicalPath: C:\inetpub\IISSite\index.html
    BindingInfo:
    - Protocol: https
      Port: 8443
      CertificateStoreName: My
      CertificateThumbprint: C676A89018C4D5902353545343634F35E6B3A659
      HostName: DSCTest
      IPAddress: '*'
      SSLFlags: 1
    - Protocol: http
      Port: 8080
      IPAddress: '*'
    AuthenticationInfo:
      Anonymous: no
      Basic: yes
      Digest: no
      Windows: yes
